// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVeQM_c4hBpFH71jviQwzLmWor-Y8JX3s',
    appId: '1:556732766209:web:d10a964bae2ecb5d97c800',
    messagingSenderId: '556732766209',
    projectId: 'wepact369',
    authDomain: 'wepact369.firebaseapp.com',
    storageBucket: 'wepact369.firebasestorage.app',
    measurementId: 'G-WM5NXPNBWH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuLaVnrdw2OwZo6_qszOmd2vN77zCeg_o',
    appId: '1:556732766209:android:c839af257a92bb5197c800',
    messagingSenderId: '556732766209',
    projectId: 'wepact369',
    storageBucket: 'wepact369.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKgp-Wa0ymBCYy5fusjIRf-dumoazPUKI',
    appId: '1:556732766209:ios:51f54258f3b1c45e97c800',
    messagingSenderId: '556732766209',
    projectId: 'wepact369',
    storageBucket: 'wepact369.firebasestorage.app',
    iosBundleId: 'com.example.wepact369',
  );
}
